---

apiVersion: v1
kind: Template
metadata:
  name: istio-pod-network-controller
  annotations:
    openshift.io/display-name: Istio Pod Network Controller Build
    description: Template to create the Istio Pod Network Controller Build Resources
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      contextDir: "${CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${FROM_IMAGE}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- name: NAME
  displayName: Name
  description: Name Applied to the Resulting ImageStream and BuildConfig
  value: istio-pod-network-controller
  required: true
- description: Image stream tag for the base application
  name: FROM_IMAGE
  required: true
  value: rhel7:7.5
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/sabre1041/istio-pod-network-controller
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR