---

apiVersion: v1
kind: Template
metadata:
  name: sa-template
  annotations:
    openshift.io/display-name: Service Acount Template
    description: Template to create a service account
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${SERVICE_ACCOUNT_NAME}"
    namespace: "${NAMESPACE}"
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: ${ROLE_NAME}
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: ${ROLE_NAME}
  roleRef:
    name: ${ROLE_NAME}
  subjects:
  - kind: ServiceAccount
    name: "${SERVICE_ACCOUNT_NAME}"
    namespace: ${NAMESPACE}
parameters:
- name: SERVICE_ACCOUNT_NAME
  displayName: Service Account Name
  description: Name of the service account to Create
  value: istio-pod-network-controller
  required: true
- name: NAMESPACE
  displayName: Namespace
  description: Namespace Containing Resources
  value: istio-pod-network-controller
  required: true
- name: ROLE_NAME
  displayName: Role Name
  description: Name of the role resources
  value: istio-pod-network-controller
  required: true
